services:
  comfyui:
    build:
      context: ./comfyui
      dockerfile: Dockerfile
      args:
        APP_USER: ${APP_USER}
        UID: ${UID}
        GID: ${GID}
    container_name: comfyui
    user: ${UID}:${GID}
    ports:
      - "8188:8188"
    volumes:
      - ./comfyui/ComfyUI:/home/${APP_USER}/ComfyUI
    environment:
      - TZ=Asia/Tokyo
      - APP_USER=${APP_USER}
      - UID=${UID}
      - GID=${GID}
      - UWGEN_API_KEY=${UWGEN_API_KEY}
      - UWGEN_API_ENDPOINT=${UWGEN_API_ENDPOINT}
    #entrypoint: ["/bin/bash"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    tty: true
